### ISSUE TITLE
EDT_METZTLI

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-entrevista-metztli_team#1]
[EDT_Metztli.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-entrevista-metztli_team/files/9854716/EDT_Metztli.pdf)

**Comment by Yabin-2021** [comment]
Buen trabajo.
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
